version: '3.7'

services:

  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: gigadb
      POSTGRES_USER: gigadb
      POSTGRES_PASSWORD: vagrant
    ports:
      - target: 5432
        published: 54321
        protocol: tcp
        mode: host
    volumes:
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
      - ${APPLICATION}/ops/configuration/postgresql-conf/test_bootstrap.sql:/docker-entrypoint-initdb.d/1-gigadb_testdata.sql
      - ${APPLICATION}/ops/configuration/postgresql-conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c 'hba_file=/etc/postgresql/pg_hba.conf'
    networks:
      - db-tier

networks:
  db-tier:

volumes:
  le_config:
  le_webrootpath: